### ISSUE TITLE
New Repo

### ISSUE THREAD

**Issue by BlaiseD** [BlaiseD/LogicBuilder.Rules#2]
@dmetzgar  @maskx - Please find the new [Repo here](https://github.com/BlaiseD/LogicBuilder.Rules).  The corresponding Nuget packages are [here (rules)](https://www.nuget.org/packages/LogicBuilder.Workflow.Activities.Rules) and [here (designer)](https://www.nuget.org/packages/LogicBuilder.Workflow.Activities.Rules.Design). 

There are some additional tests and a new namespace [as recommended](https://github.com/dotnet/corefx/issues/24410#issuecomment-354857643) but otherwise the code is the same.

The old package Nuget pages now have "deprecated" notices and will be unlisted at some point.

**Comment by dmetzgar** [comment]
Thanks @BlaiseD

**Comment by maskx** [comment]
Thanks @BlaiseD

**Comment by BlaiseD** [comment]
np
