### ISSUE TITLE
Grouping of Condition

### ISSUE THREAD

**Issue by djsx** [BlaiseD/LogicBuilder.Rules#3]
Excellent Work!! Highly Appreciate.

Is there a possibility of Grouping/Scoping Conditions?
Example would be "Account is Active AND (Balance > 100 OR CreatedOn > 4 years) AND Country is US"

**Comment by BlaiseD** [comment]
Sure - grouping is possible.  I assume "Account is Active" is pseudo code.   The quickest way to verify is through the [Rule-set Editor](https://github.com/BlaiseD/LogicBuilder.Rules#rule-set-editor).

**Comment by djsx** [comment]
Yes, It worked fine. I was going through Test Cases. Rule-Set Editor is better

**Comment by BlaiseD** [comment]
ok.  PRs are welcome for additional test cases.
